<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>ilmarinen-discord-bot</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.18.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.14" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ilmarinen.NotificationClient\Ilmarinen.NotificationClient.csproj" />
    <ProjectReference Include="..\Ilmarinen.Protocol\Ilmarinen.Protocol.csproj" />
  </ItemGroup>

</Project>
